name: Backend deployment to server

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deployment
        id: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            
            cd /var/www/piggy
            
            echo "Pulling the latest code from the repository"
            git fetch origin
            git reset --hard origin/main

            echo "Delete old package-lock"
            rm -rf package-lock.json
            rm -rf node_modules

            echo "Installing dependencies"
            npm install
            
            echo "Building the project"
            npm run build
                        
            echo "Deployment completed successfully"